### ISSUE TITLE
windows : error when git comit 

### ISSUE THREAD

**Issue by trikinoah** [SA-EME/GitBenchmark#2]
```
Traceback (most recent call last):
  File "C:\Users\trikino\Documents\Projects\GitBenchmark\src\main.py", line 16, in <module>
    args.func(args)
  File "C:\Users\trikino\Documents\Projects\GitBenchmark\src\arguments\commit.py", line 36, in commit_arguments
    commit(type, scope, message)
  File "C:\Users\trikino\Documents\Projects\GitBenchmark\src\controllers\commit.py", line 65, in commit
    execute_command(f"git commit -m '{commit_message}'")
  File "C:\Users\trikino\Documents\Projects\GitBenchmark\src\utils.py", line 7, in execute_command
    process = subprocess.run(command, shell=True, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\trikino\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'git commit -m 'chore(frontend): modify banner text'' returned non-zero exit status 1
```

modify ' to "

**Comment by KalvinVilla** [comment]
fix by fc56ed8135e349c0d84ee1fa73bab7bc9b550389
